//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seec.Marketing.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seec.Marketing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT 
        ///     S1.CUSTOMER_ID
        ///    ,S1.LAST_UPDATE_DATE --by fan
        ///    ,S1.CUSTOMER_NUMBER
        ///    ,S1.CUSTOMER_NAME
        ///    ,S1.SHIP_ADDRESS_ID
        ///    ,S1.BILL_ADDRESS_ID
        ///    ,S1.SHIP_ADDRESS1
        ///    ,S1.BILL_ADDRESS1
        ///    ,S1.CUSTOMER_CATEGORY_CODE
        ///    ,S1.MEANING
        ///    ,S1.SHIP_TO_SITE_USE_ID
        ///    ,S1.INVOICE_TO_SITE_USE_ID
        ///    ,S1.ORDER_TYPE_ID
        ///    ,S1.TYPE_NAME
        ///    ,S1.PRICE_LIST_ID
        ///    ,S3.CURRENCY_CODE --by fan
        ///    ,S1.SALESREP_ID
        ///    ,S1.SALES_NAME
        ///    ,S2.AREA_CODE
        ///    ,S2.PHONE
        ///    ,S2.CONTACT_ID
        ///  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string CustomersSyncSql {
            get {
                return ResourceManager.GetString("CustomersSyncSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT
        ///SD.DISCOUNT_ID,
        ///SD.NAME DISCOUNT_NAME,
        ///SD.AUTOMATIC_DISCOUNT_FLAG,
        ///SD.OVERRIDE_ALLOWED_FLAG,
        ///SP.PRICE_LIST_ID,
        ///SP.NAME LIST_NAME,
        ///--DECODE(SD.ATTRIBUTE15,&apos;XS_HEAD_D&apos;,&apos;內銷表頭&apos;,&apos;XS_LINE_D&apos;,&apos;內銷明細&apos;,&apos;XS_HEAD_O&apos;,&apos;外銷表頭&apos;,&apos;XS_LINE_O&apos;,&apos;外銷明細&apos;) DISCOUNT_TYPE,
        ///DECODE(SD.ATTRIBUTE15,&apos;XS_HEAD_D&apos;,1,&apos;XS_LINE_D&apos;,2,&apos;XS_HEAD_O&apos;,3,&apos;XS_LINE_O&apos;,4) DISCOUNT_TYPE,
        ///SD.LAST_UPDATE_DATE
        ///FROM OE.SO_DISCOUNTS SD,
        ///     OE.SO_PRICE_LISTS SP
        ///WHERE
        ///    SP.NAME LIKE &apos;%廈門%&apos;
        ///AND SP.END_DATE_ACTIVE IS NULL
        ///AND SD.END_DATE_AC [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string DiscountsSyncSql {
            get {
                return ResourceManager.GetString("DiscountsSyncSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT   MSI.INVENTORY_ITEM_ID, CA.ITEM, MSI.DESCRIPTION,CA.UNIT_WEIGHT,CA.WEIGHT_UOM_CODE, CA.DISCOUNT,CA.SEGMENT1,
        ///         CA.SEGMENT2, CA.SEGMENT3, MSI.ORGANIZATION_ID, MP.ORGANIZATION_CODE,
        ///         MSI.ENABLED_FLAG, MSI.LAST_UPDATE_DATE
        ///    FROM MTL_SYSTEM_ITEMS MSI,
        ///         (SELECT MSI.ORGANIZATION_ID, MSI.INVENTORY_ITEM_ID,
        ///                 MSI.SEGMENT1 ITEM, MC.SEGMENT1, MC.SEGMENT2, MC.SEGMENT3,MSI.UNIT_WEIGHT,MSI.WEIGHT_UOM_CODE,XCD.DISCOUNT
        ///            FROM OE.XSEEC_CATEGORY_DISCOUNT XCD, [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string InventorySyncSql {
            get {
                return ResourceManager.GetString("InventorySyncSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SELECT 
        ///SPL.LIST_NAME 
        ///    ,SPL.PRICE_LIST_ID
        ///    ,MSI.INVENTORY_ITEM_ID
        ///    ,MSI.SEGMENT1 
        ///    ,MSI.PRIMARY_UNIT_OF_MEASURE 
        ///    ,MSI.DESCRIPTION 
        ///    ,SPL.LIST_PRICE 
        ///    ,SPL.CURRENCY_CODE 
        ///
        ///FROM INV.MTL_SYSTEM_ITEMS MSI
        ///
        ///    ,(SELECT MSI.SEGMENT1 ITEM
        ///            ,MSI.INVENTORY_ITEM_ID
        ///            ,MSI.DESCRIPTION
        ///            ,SPL.LIST_PRICE
        ///            ,SPL.PRICE_LIST_ID
        ///            ,SP.NAME LIST_NAME
        ///            ,SP.CURRENCY_CODE
        ///        FROM  OE.SO_PRICE_LISTS SP
        ///             ,OE. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string PriceBookSyncSql {
            get {
                return ResourceManager.GetString("PriceBookSyncSql", resourceCulture);
            }
        }
    }
}
